## データソース設定
spring:
  datasource:
    ## worldDB
    world:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://worlddb:5432/worlddb?allowMultiQueries=true
      username: api
      password: password
    ## usersDB
    users:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://userdb:5432/usersdb
      username: api
      password: password
## ログレベルの指定
logging:
  level:
    com:
      example:
        demo:
          repository: DEBUG